/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testpackage_TestLaunch015 */

#ifndef _Included_testpackage_TestLaunch015
#define _Included_testpackage_TestLaunch015
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testpackage_TestLaunch015
 * Method:    nativeTestMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_testpackage_TestLaunch015_nativeTestMethod
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
